const Market = [
  {store: '옛날국밥', number:'xxx-xxxx-xxxx',  key: '0000'},
  {store: '밥도둑 얼큰애호박찌개', number:'xxx-xxxx-xxxx',  key: '0001'},
  {store: '나홀로 부대찌개', number:'xxx-xxxx-xxxx',  key: '0002'},
  {store: '털보삼촌 돼지찌개', number:'xxx-xxxx-xxxx',  key: '0003'},
  {store: '참맛집', number:'xxx-xxxx-xxxx',  key: '0004'},
  {store: '이바돔감자탕', number:'xxx-xxxx-xxxx',  key: '0005'},
  {store: '무등연탄석쇠불고기', number:'xxx-xxxx-xxxx',  key: '0006'},
  {store: '또또 도시락&반찬', number:'xxx-xxxx-xxxx',  key: '0007'},
  {store: '1인한식당', number:'xxx-xxxx-xxxx',  key: '0008'},
  {store: '상지국밥', number:'xxx-xxxx-xxxx',  key: '0009'},
  {store: '또또 도시락&반찬', number:'xxx-xxxx-xxxx',  key: '0010'},
  {store: '청진동해장국', number:'xxx-xxxx-xxxx',  key: '0011'},
  {store: '한우 진 설농탕', number:'xxx-xxxx-xxxx',  key: '0012'},
  {store: '한국관', number:'xxx-xxxx-xxxx',  key: '0013'},
  {store: '성수동꿀꽈베기', number:'xxx-xxxx-xxxx',  key: '0014'},
  {store: '떡도그', number:'xxx-xxxx-xxxx',  key: '0015'},
  {store: '큰손분식떡볶이상추튀김김치찌개', number:'xxx-xxxx-xxxx',  key: '0016'},
  {store: '인정국물떡볶이 광주1호점', number:'xxx-xxxx-xxxx',  key: '0017'},
  {store: '소품떡', number:'xxx-xxxx-xxxx',  key: '0018'},
  {store: '24시 서울김밥', number:'xxx-xxxx-xxxx',  key: '0019'},
  {store: '마피아떡볶이', number:'xxx-xxxx-xxxx',  key: '0020'},
  {store: '현완단겸 상추튀김', number:'xxx-xxxx-xxxx',  key: '0021'},
  {store: '스쿨푸드', number:'xxx-xxxx-xxxx',  key: '0022'},
  {store: '상무김밥', number:'xxx-xxxx-xxxx',  key: '0023'},
  {store: '가인 초밥', number:'xxx-xxxx-xxxx',  key: '0024'},
  {store: '스시도감', number:'xxx-xxxx-xxxx',  key: '0025'},
  {store: '의리수제돈까스', number:'xxx-xxxx-xxxx',  key: '0026'},
  {store: 'BBQ 치평본점', number:'xxx-xxxx-xxxx',  key: '0027'},
  {store: '치요남치킨', number:'xxx-xxxx-xxxx',  key: '0028'},
  {store: '깻잎두마리치킨', number:'xxx-xxxx-xxxx',  key: '0029'},
  {store: '페리카나', number:'xxx-xxxx-xxxx',  key: '0030'},
];

export default Market;
