require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Loger_RN_Qari' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"

  

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

end
